### ISSUE TITLE
How to prevent "Adjusted frame length exceeds XXX" errors

### ISSUE THREAD

**Issue by feedhandler** [datastax/dsbulk#389]
Hi, 

I get some errors from dsbulk unload like this:

```
com.datastax.oss.dsbulk.executor.api.exception.BulkExecutionException: Statement execution failed: SELECT [...statement here...] (Adjusted frame length exceeds 268435456: 333267766 - discarded)
```

It looks like the query result has exceeded the native_transport_max_frame_size_in_mb limit (256MB)

Is there a dsbulk config setting I can change that will reduce the size of the results from that query (and hopefully prevent that error) ?

Thanks

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/BULK-14) by [Unito](https://www.unito.io)

**Comment by adutra** [comment]
Hi @feedhandler if you are encountering this error when reading, you could first try to reduce the page size. The default is 5000 rows. You can change this value with `--driver.basic.request.page-size 1000` for example.

If that does not work, then you can also increase the maximum frame length. Beware that this needs to be done both in DSBulk and in Cassandra, so that client and server have the same value.
 * Server-side, this can be configured with [`native_transport_max_frame_size_in_mb`](https://cassandra.apache.org/doc/stable/cassandra/configuration/cass_yaml_file.html#native_transport_max_frame_size_in_mb) as you pointed out;
* In DSBulk, you can change the default 256 MiB limit with `--driver.advanced.protocol.max-frame-length '512 MiB'` for example.

Let me know if that helps. Thanks!

**Comment by feedhandler** [comment]
ok, thanks. I will try that.

**Comment by acscott** [comment]
In C* config I have: `# native_transport_max_frame_size_in_mb: 256`
but I had to use
`--driver.advanced.protocol.max-frame-length '513 MiB'` for dsbulk on the command line.  It doesn't work setting it in `dsbulk.conf`.
The error I was getting was: `Caused by: com.datastax.oss.driver.api.core.connection.FrameTooLongException: Adjusted frame length exceeds 268435456: 268880055 - discarded` which adds up to 512.42 MiB

**Comment by ag26jan** [comment]
This setting is still not available out of the box in dsbulk, am I missing something?
